CREATE TABLE public.committee
(
    committee_id serial,
    name character varying(500) NOT NULL,
    typeid character varying(500) NULL,
	committee_contact_id integer NULL,
	other_contact_id integer NULL,
	treasurer_contact_id integer NULL,
	candidate_contact_id integer NULL,
	office_sought_id character varying(50) NULL,
    district character varying(150) NULL,
	election_cycle_id integer NULL,
	ballot_issue_id integer NULL,
	ballot_issue_notes character varying(150) NULL,
    position character varying(50) NULL,
    purpose character varying(1000) NULL,
    campaign_website character varying(200) NULL,
	bank_name character varying(150) NULL,
	bank_address1 character varying(200) NULL,
	bank_address2 character varying(200) NULL,
	bank_city character varying(150) NULL,
	bank_state_code character varying(2) NULL,
    bank_zip character varying(10) NULL,
	registration_status character varying(10) NULL,
    admin_notes character varying(500) NULL,
	status_code character varying(10) NULL,
	created_by character varying(100) NULL,
	created_at date NULL,
	updated_by character varying(100) NULL,
	updated_on date NULL,
    CONSTRAINT committee_pkey PRIMARY KEY (committee_id)
)